# -*- coding: utf-8 -*-
"""Copia de Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i_4mI4ST4TSEY8aCFqe8kGgVmuG6t22K
"""

def calcular_descuento(monto, porcentaje=10):
    return monto * (porcentaje / 100)

# Primera llamada
monto1 = 100
descuento1 = calcular_descuento(monto1)
final1 = monto1 - descuento1

# Segunda llamada
monto2 = 200
descuento2 = calcular_descuento(monto2, 20)
final2 = monto2 - descuento2

# Mostrar resultados
print(f"Monto: {monto1}, Descuento: {descuento1}, Final: {final1}")
print(f"Monto: {monto2}, Descuento: {descuento2}, Final: {final2}")