# -*- coding: utf-8 -*-
"""Tarea_Python_Eliana.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YXsQBSyyICyCdGaaAa-zKe_SFrXDz8r7
"""

# Saludo
nombre = "Eliana"
print("Hola, " + nombre + "!")

# Matriz 3x3
matriz = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print("\nLa matriz 3x3 es:")
for fila in matriz:
    print(fila)

# Función para buscar un valor en la matriz
def buscar_valor(matriz, valor):
    for i in range(len(matriz)):
        for j in range(len(matriz[i])):
            if matriz[i][j] == valor:
                return f"Valor {valor} encontrado en la fila {i+1}, columna {j+1}"
    return f"Valor {valor} no encontrado en la matriz"

# Definimos el valor a buscar
valor_a_buscar = 5

# Llamamos a la función
resultado = buscar_valor(matriz, valor_a_buscar)
print("\n" + resultado)
# Función para buscar un valor en la matriz y devolver su posición
def buscar_valor(matriz, valor):
    for i in range(len(matriz)):
        for j in range(len(matriz[i])):
            if matriz[i][j] == valor:
                return (i+1, j+1)  # fila y columna
    return None

# Valor que queremos buscar
valor_a_buscar = 5

# Llamamos a la función
posicion = buscar_valor(matriz, valor_a_buscar)

# Mostramos el mensaje según se encuentre o no
if posicion:
    print(f"El valor {valor_a_buscar} sí se encontró en la fila {posicion[0]}, columna {posicion[1]}.")
else:
    print(f"No se encontró el valor {valor_a_buscar} en la matriz.")